### ISSUE TITLE
Deletion bypasses Windows recycle bin

### ISSUE THREAD

**Issue by kAlvaro** [kdcro101/vscode-favorites#10]
I've just had to restore a file from my backup copy because I chose the *Delete* item from the context menu in the *Favorite* panel (naively believing that it would only remove it from the favourites list).

When I remove local files anywhere else on Visual Studio Code files are sent to recycle bin. It'd be nice that the addon would do the same (as long as the extension API allows it). I'm using Visual Studio Code x64 on Windows 10.

**Comment by kdcro101** [comment]
`Delete` is same as `Delete` from vscode file explorer. 
To remove item from favorites use `Remove from favorites`.

You have confirmation question `Are you sure you want to delete 'filename.ext'` popup to confirm.
If you confirm, file gets deleted.

Use git so you can discard changes (vscode has built-in support for it).

If you need private repositories use [gitlab](https://about.gitlab.com/)
