### ISSUE TITLE
Potential to store settings somewhere else

### ISSUE THREAD

**Issue by theomjones** [kdcro101/vscode-favorites#13]
I was wondering if there might be a way settings can be stored somewhere other than `settings.json`. In my team we have `.vscode/settings.json` checked in as we have certain useful things such as excluding build/compile directories from search and the file tree. But of course checking in Favourites changes is an issue in a shared workspace.

This is more of an issue to invoke discussion, rather than an immediate feature request.

**Comment by kdcro101** [comment]
@theomjones ,

Thank you for your feedback.

I am planning to move storage of favorite items definitions from workspace to file `.favorites.json` in workspace root. To do that I have to make some fundamental changes.

I will keep you posted here

**Comment by ybilianskey** [comment]
Probably, moving favorites settings to dedicated location should fix another issue: each favorites version update deletes user-selected colors (svg-generated folder). That's frustrating :(

**Comment by kdcro101** [comment]
@ybilianskey ,

Thank you for your feedback!

Sorry to hear you have problems with colors.
I will fix that in next update!

Please open issue if you have suggestion or bug to report.

**Comment by kdcro101** [comment]
@ybilianskey ,

Update to `1.9.6`. Problem should be fixed.

Please, let mi know how it went!

If you have any problems open issue.

**Comment by ybilianskey** [comment]
It was a super-fast fix and it works fine know. Thank you very much for nice add-in and level of support that is simply fantastic!

**Comment by kdcro101** [comment]
@ybilianskey ,

No problem!
Glad to hear that problem is gone and that extension works out for you!

**Comment by kdcro101** [comment]
@theomjones ,

Please update to `2.0.0.`. Favorites are are stored in workspace root as file `.favorites.json`. In case of multiroot workspace, file is located in first workspace.

If you have any problems, open issue.

**Comment by MarekLew** [comment]
I like stored favorites in `.code-worksapces` file. It would be good if this option existed.
