### ISSUE TITLE
Folder recovery

### ISSUE THREAD

**Issue by Nabeu** [kdcro101/vscode-favorites#14]
Hello i need your help. I had a folder with more than 10 cpp changed files as favorite. I tried to delete the folder from Favorites banner. And now i can´t find folder and files any where. It delete it permanently. Please i need your help urgent.

**Comment by kdcro101** [comment]
@Nabeu ,

I can't help you. If you deleted folder it is deleted.

If you want to remove items from favorites use `Remove from favorites`

**Comment by Nabeu** [comment]
But after delete where can i find it? i could not find it in trash!

**Comment by kdcro101** [comment]
I am honestly sorry you are having problems, but i think your files are [deleted](https://en.wikipedia.org/wiki/File_deletion)

**Comment by kdcro101** [comment]
There is a undocumented configuration item `favorites.useTrash:boolean` but i have to test it (you can use it, at your own risk, by enabling it in global/workspace settings ).

Problem is that 'moving to trash' operation is different for each operating systems vscode operates on (windows,linux,macos). It is not simple operation nor operating systems commit resources to trash every time file gets deleted (thousands of temporary files of various sizes gets created and deleted on each session you use your system). 

You can avoid this scenario by using version control system (git/subversion,etc.) or regular backups.

If you need free private git repositories, I would suggest [gitlab](https://about.gitlab.com/)
