### ISSUE TITLE
Ignore excluded files on TreeView

### ISSUE THREAD

**Issue by StanleySathler** [kdcro101/vscode-favorites#17]
Hey guys,
Thanks for the awesome work!

I could notice the Favorite TreeView also lists files that are included in the `files.exclude` setting. Should we also consider this option while listing the files, just like the original TreeView does?

**Comment by kdcro101** [comment]
@StanleySathler ,

Thank you for your feedback.

I am planning to filter out excluded patterns.

I will keep you posted here.

**Comment by StanleySathler** [comment]
Hey @kdcro101

Thanks for answering. I'd be very happy to contribute to the project by submiting a PR for this.

**Comment by kdcro101** [comment]
@StanleySathler ,

Thank you for offering help. I really appreciate it.
To implement this functionality, I had to make some deep changes.

Please update to `2.1.2`. Files/Directories/Favorites matched by patterns defined in `files.exclude` will be excluded.

You can turn feature off by setting `favorites.useFilesExclude` to `false` (default is `true`).

If you have any problems, open issue.
