### ISSUE TITLE
Place .favourites.json inside .vscode folder

### ISSUE THREAD

**Issue by Yanpas** [kdcro101/vscode-favorites#18]
Currently it introduces a lot of noise with svn / git

**Comment by kdcro101** [comment]
@Yanpas ,

Thank you for your feedback.

I have annouced location in #13. 
What kind of "noise" do you mean?

**Comment by kdcro101** [comment]
@theomjones, 
what is your take on this?

**Comment by Yanpas** [comment]
This file is marked as unversioned and I have blue badge "1" .

Many vscode extensions place their data to .vscode (cquery, cpp, sftp e.g.). It's easy to clean all .vscode settings simply removing this directory.

`.vscode/favorites.json` is more conventional IMO.

**Comment by kdcro101** [comment]
@Yanpas ,

~~I also think that `.vscode/favorites.json` is better location.~~

Please update to `2.0.1`. 
Location of favorites is in `.vscode/favorites.json` in workspace folder. In case of multiroot project, it is located in same location in first workspace.

Thank you for your feedback.

If you have any problems, open issue.

**Comment by Yanpas** [comment]
Thank you 🤝

**Comment by MarekLew** [comment]
**Location of favorites is in `.vscode/favorites.json` in workspace folde**? I hanged workspace order or add/delete it automatically. Please add link to file(favorites.json) in work WORKSPACE SETTINGS.

**Comment by theomjones** [comment]
Nice work @kdcro101! I think this is a great solution!

**Comment by kdcro101** [comment]
@theomjones ,

Thanks! Glad you like it

**Comment by hsandt** [comment]
Nice!

Note that you can also set `favorites.storageFilePath` in the User Settings, as it will still use a path relative to the workspace.

In my opinion, `.vscode/favorites.json` should be the default, but it's not a big deal as long as users can tweak this just by having a look at the plugin settings. Once you configured it in the User Settings, it should apply to all workspaces anyway.
