### ISSUE TITLE
favorites.json location

### ISSUE THREAD

**Issue by MarekLew** [kdcro101/vscode-favorites#19]
Form #18 👎 **Location of favorites is in `.vscode/favorites.json` in workspace folde**? I hanged workspace order or add/delete it automatically. Please add link to file(favorites.json) in work WORKSPACE SETTINGS.

if link exist in `xxx.code-workspace` then use favorites.json from ther.

**Comment by kdcro101** [comment]
@MarekLew ,


Please update to `2.0.2`. I've  added configuration item `favorites.storageFilePath`.
Set `favorites.storageFilePath` as path relative to your workspace, for example: `settings/favorites.json` or `config/myFavorites.json`

Default is `.favorites.json`.

If you have any problems, open  issue.

**Comment by MarekLew** [comment]
@kbcro101
You use relative path to first workspace folder? Please add `${workspaceFolder:a}` variable to select workspace path.

Example:
`"favorites.storageFilePath": "${workspaceFolder:a}/.favorites.json"`

PS. I like stored favorites in `.code-worksapces` file.  It would be good if this option existed.

**Comment by kdcro101** [comment]
@MarekLew , 

Predefined variables work only in `launch.json` and `tasks.json`. They are not supported in `user` and `workspace` settings, `*.code-workspace` file (settings section) or extensions `package.json` where default value is defined ( as per documentation).

**Comment by MarekLew** [comment]
"relative path to first or indexing workspace" is not good idea, please add absolute path option .  #32.

**Comment by MarekLew** [comment]
> Predefined variables work only in `launch.json` and `tasks.json`. They are not supported in `user` and `workspace` settings, `*.code-workspace` file (settings section) or extensions `package.json` where default value is defined ( as per documentation).

This is problem  replease "${workspaceFolder:\w*}" to selected workspace path.

**Comment by kdcro101** [comment]
@MarekLew ,

If you need other then first workspace, you can select it with config `favorites.useWorkspace`.

Does it helps?

**Comment by MarekLew** [comment]
I change/add/move/remove workspaces folders in *.code-workspace. It's not for me. Absolute path or named workspace path or old storage in *.code-workspace but not relative path and indexing workspace.

**Comment by MarekLew** [comment]
> 
> 
> @MarekLew ,
> 
> If you need other then first workspace, you can select it with config `favorites.useWorkspace`.
> 
> Does it helps?

No this not helped.
