### ISSUE TITLE
Missing favorites

### ISSUE THREAD

**Issue by csicky** [kdcro101/vscode-favorites#20]
Hi, thanks for this helpful extension. Today I see the favorites are not visible anymore, instead I receive this error in the screenshot. Please let me know what other info you need in order to be able to investigate this.

Version 2.1.2

![image](https://user-images.githubusercontent.com/3931907/47293386-a9b88e00-d612-11e8-9c5d-4e9133d8bde3.png)

**Comment by andersomsousa1406** [comment]
I'm also having the same problem

**Comment by kdcro101** [comment]
@csicky , @andersomsousa1406,

Thank you for your feedback.

Please post your `.favorites.json` contents.
There was some `favorites.json` structure modification.

**Comment by csicky** [comment]
```
[
    {
        "type": "File",
        "name": "d:\\folderName\\src\\modules\\translations.js",
        "parent_id": null,
        "workspacePath": "src\\modules\\translations.js",
        "id": "esuvqW3gCJmDarOV"
    },
    {
        "type": "File",
        "name": "d:\\folderName\\src\\modules\\utils.js",
        "parent_id": null,
        "workspacePath": "src\\modules\\utils.js",
        "id": "GIcbfgMBDt0mSAK7"
    },
    {
        "type": "File",
        "name": "d:\\folderName\\src\\store\\getters.js",
        "parent_id": null,
        "workspacePath": "src\\store\\getters.js",
        "id": "GrbTs18C0gXmeYUK"
    }
]
```

Here it is, but I guess in this case it's enough to remove the files and add them again and I will have the new JSON.

**Comment by csicky** [comment]
Wow, you are so fast! Thank you for the fix, I have now version 2.1.4 and the favorites are back.

**Comment by kdcro101** [comment]
@csicky ,

I am just typing :
Please update to vesion `2.1.5`. Problem should be fi

**Comment by kdcro101** [comment]
@csicky ,

Thank you for your feedback.

Latest version is `2.1.5` 

If you have any problems, open issue.
