### ISSUE TITLE
Side panel height

### ISSUE THREAD

**Issue by csicky** [kdcro101/vscode-favorites#21]
I just want to share here too a little problem with the side panel height jumping as I close the files. I reported it to VS Code, but maybe you can do something about it on your side?

https://github.com/Microsoft/vscode/issues/60266

**Comment by kdcro101** [comment]
@csicky ,

Nothing to do on my side. 

This is vscode behaviour. Problem is variable height of `Open editors` subview + fixed height of Workspace file explorer + rest of height for favorites.
Increase of height of `Favorites` subview is result of filling rest of height.

You can:
- Drag `favorites` above file explorer
or
- don't use `favorites` subview for File explorer and use dedicated view accessible from activity bar (heart icon on left).

You can turn off `favorites` subview by clicking its header and deselecting `favorites` item

**Comment by csicky** [comment]
Thank you for taking the time to look into it.

**Comment by kdcro101** [comment]
No problem!
