### ISSUE TITLE
Folders added to favorites don't reflect file changes

### ISSUE THREAD

**Issue by arfordweb** [kdcro101/vscode-favorites#24]
If I create a group for favorites and add a folder to that group, I can see that folder and all its files and subfolders in my favorites list.  But, if I add a file to that folder in the normal file explorer, I don't see that added file reflected in my favorites.

It would be nice if it would detect file renamings, additions, or deletions automatically.  If that's too difficult, it would be nice if the Favorites panel had a refresh button that would refresh the contents of those folders.

**Comment by kdcro101** [comment]
@arfordweb ,

Thank you for your feedback.

Please update to version `2.2.1`. Problem should be fixed.
For external resources use `refresh` button  on top of `favorites explorer`.

If you have any problems, open issue.

**Comment by arfordweb** [comment]
@kdcro101 Awesome!  That's a pretty stellar turnaround time for a GitHub issue.  Many thanks!
