### ISSUE TITLE
Extension creates .vscode/settings.json in new folders

### ISSUE THREAD

**Issue by Yanpas** [kdcro101/vscode-favorites#25]
When I open new folder in vs code this extension creates `.vscode/settings.json` with the following content:
```json
{
    "favorites.sortDirection": "ASC",
    "favorites.groupsFirst": true
}
```

**Comment by kdcro101** [comment]
@Yanpas ,

Thank you for your feedback!

Please update to version `2.2.2`. Problem should be fixed.

If you have any problems, open issue.
