### ISSUE TITLE
Invalid favorites.json file makes extension go infinite progress bar

### ISSUE THREAD

**Issue by Yanpas** [kdcro101/vscode-favorites#27]
Sometimes when I compile my project the load is high and if I update favorites.json it gets dumped to disc in several writes. If extension parses it when the file is not completely written. I see this:
![image](https://user-images.githubusercontent.com/7345761/47581958-a0edf200-d95b-11e8-8345-0927ee61c9f2.png)

Solution: Extension should silently retry to load favorites.json several times and then report after some timeout that there was an error.

Easy to reproduce if I append some garbage to file with json

**Comment by kdcro101** [comment]
When there is an error it resolves to an empty array.
You can manually refresh favorites to force it to reload.

fsWatcher is needed (see #24) to refresh view when favorites contents are changed.
Event handler is debounced so there is no excess CPU load.
