### ISSUE TITLE
Suggestion: Possibility to create alias for file or folder

### ISSUE THREAD

**Issue by Emerson-Coelho** [kdcro101/vscode-favorites#3]
Would it be possible to create an alias option for file or folder?
In my file structure, I have files and folders with the same name.
With this option, I can distinguish the sources.

Example :

![example](https://user-images.githubusercontent.com/23087550/39578465-a231c79e-4eba-11e8-92ee-844413e4713c.jpg)

**Comment by kdcro101** [comment]
@Emerson-Coelho 

Check out version 1.3.0

what is new?

- favorite items can have alias (custom display label)
- groups can be renamed
- favorites can be accesed via activity bar

**Comment by Emerson-Coelho** [comment]
You are the best!!!
Very, very good!!!

**Comment by kdcro101** [comment]
@Emerson-Coelho 

I'm glad you like it.

Since it is now perfect (for you). Can I ask you, if you have time, to post   5-star review at:
https://marketplace.visualstudio.com/items?itemName=kdcro101.favorites#review-details

**Comment by kdcro101** [comment]
@Emerson-Coelho 
Thanks for you feedback
