### ISSUE TITLE
Command to open favorite

### ISSUE THREAD

**Issue by PaulPichaureau** [kdcro101/vscode-favorites#31]
It could be interesting to have a command "Open favorite".

This command could be associated to a keyboard shortcut to quickly access to a favorite.

This could be an excellent time saver!

**Comment by kdcro101** [comment]
@PaulPichaureau ,

You want browsing of favorites via command palette?

It is doable, I will keep you posted here.

**Comment by kdcro101** [comment]
@PaulPichaureau ,

Please update to version `2.4.2`. Keyboard browsing via command palette is implemented.

How to use:

- select `Favorites: Browse` from command palette (assign keyboard shortcut if needed)
- type to filter list
- select directory or group to enter or file to open

When executing command `Favorites: Browse` while focused on file that is accessible via favorites, navigation will start in directory of currently active document.

If you have any problems, open issue.

**Comment by PaulPichaureau** [comment]
Seems to work! Great job!
