### ISSUE TITLE
Favorites storage path being relative to workspace interferes with repository

### ISSUE THREAD

**Issue by Yzrsah** [kdcro101/vscode-favorites#33]
This extension puts files into the project directory. This causes problems with different people's personal favorites files being checked into the repo. So all projects need to have a ruleset posted ahead of time with setup and post-setup steps to gitignore the file and then be sure not add in .favorites.json, otherwise the devs favorites files will come into conflict.

I use other some extensions which don't have this problem. I.e.
https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

**Comment by kdcro101** [comment]
@Zyrsha ,

Thank you for your feedback.

Can you, please, check [this](https://github.com/kdcro101/vscode-favorites/issues/28) thread?
Let me know if it works for you.
