### ISSUE TITLE
command 'favorites.XXX' not found

### ISSUE THREAD

**Issue by Amanpeet** [kdcro101/vscode-favorites#36]
after installing the extension, the commands are in F1 panel but they do not work. any command i try to run or even click on icons at favorites directory bar, all show same error like
**command 'favorites.group.create' not found**
plz help.

**Comment by mellevsen** [comment]
Same problem. Functionality looks good, but not working at all beyond displaying Favorites panel.

Using Insiders w/ only other extension for C# language.

**Comment by kdcro101** [comment]
@Galzor , @mellevsen ,


Most common thing users of this extension do is to assume this is extension for favorites on global level - without opening workspace.

**Workspace needs to be opened** to use  this extension.

Please give me heads-up if that is your case.

**Comment by Amanpeet** [comment]
oh yes, you are right. it is working fine in workspace, but than it is not what i needed. can you add this to suggestion plz: **Add something like global favorites.**
