### ISSUE TITLE
Can't find favorites.json

### ISSUE THREAD

**Issue by fharper** [kdcro101/vscode-favorites#37]
Hi, I think with the last update of VSCode, I lost my favorites (or maybe I did something), anyhow, not critical. I added again the favorites and it's working, but I can't find any .favorites.json file anywhere (I thought it should be by default in the workspace folder). Where are those saved? I would like to backup this file... Thanks

**Comment by kdcro101** [comment]
@fharper ,

Configuration `favorites.storageFilePath` overrides default storage path relative to workspace root. 
In case of multi-root workspaces you can use `favorites.useWorkspace` to set which workspace to use to determine "root".

If you have more questions, open issue.

**Comment by fharper** [comment]
@kdcro101

The only `favorites.json` I have on my computer is `~/.vscode/extensions/kdcro101.favorites-2.4.5/.favorites.json` and only content a square bracket. The `favorites.storageFilePat` is empty, the favorites are there, which is weird.
