### ISSUE TITLE
Add favorites as activity bar item instead of panel in explorer item

### ISSUE THREAD

**Issue by PixelT** [kdcro101/vscode-favorites#4]
More details about this:
https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by kdcro101** [comment]
@PixelT 

Please, check out latest version (1.3.0).

Thanks for feedback.

**Comment by PixelT** [comment]
Hmm, I don't know what was earlier, but now the 'Collapse all' button doesn't work for me.

**Comment by kdcro101** [comment]
@PixelT 

Just tested on few projects. It works on my side.
Can you describe in more detail?

**Comment by PixelT** [comment]
OK, 'Collapse all' work, I added files in wrong way, sorry for that :)

**Comment by kdcro101** [comment]
@PixelT 

You can add active document to favorites by pallete command:
`Add active document to favorites`

You can assign keybinding too.

Command you mentioned are for use with explorer view item.

**Comment by kdcro101** [comment]
Closing... 

- Activity bar  [DONE]
- Collapse all [WORKS]

**Comment by PixelT** [comment]
One question, because Favourites are now in activity bar, it's possible to remove it from Explorer?

**Comment by kdcro101** [comment]
Yes, it is possible to remove view from explorer if you don't need it.
You can always access favorites from activity bar view.

**Comment by PixelT** [comment]
You misunderstood me - I want to remove 'Favorites' Tab from Explorer, because it's now in 2 places:
- Explorer -> Favorites Tab
- Favorites in activity bar
