### ISSUE TITLE
Add file to favourite by UI

### ISSUE THREAD

**Issue by PixelT** [kdcro101/vscode-favorites#5]
It will be good to possibility to add / remove active file to favourites in another way than palette command `Add active document to favorites`
Maybe position in context menu after mouse right-click?

Delete favourite file from palette command doesn't work:
```Running the contributed command:'favorites.deleteFavorite' failed.```

**Comment by PixelT** [comment]
Update: the whole palette commands doesn't work for me:
```You have to call this extension from explorer```

**Comment by kdcro101** [comment]
Yes.
You have to call it from explorer

**Comment by PixelT** [comment]
OK, now I see how it works ;) so my first post is still actual here ;) to add possibility to add / remove file using context menu

**Comment by kdcro101** [comment]
@PixelT

You can add active document to favorites by palette command:

`Add active document to favorites`
You can assign keybinding too.

You can add file/directory to favorites with following methods
1. `Add active document to favorites` from palette command (or optional keybinding)
2. Right click on object in file explorer and select `Add to favorites`

**Comment by kdcro101** [comment]
Please, read https://github.com/kdcro101/vscode-favorite-items/blob/master/README.md
