### ISSUE TITLE
Proposed API is only available when running out of dev...

### ISSUE THREAD

**Issue by subz390** [kdcro101/vscode-favorites#50]
**Describe the bug**
Since today's update, VSCode v1.47.0 constantly shows this message.
![200710 message](https://user-images.githubusercontent.com/11546815/87117520-b2cb1200-c270-11ea-9c33-d1845663da67.png)

`[kdcro101.favorites]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api kdcro101.favorites`

**To Reproduce**
update to the current version of VSCode
message appears automatically

**Expected behavior**
for there to be no message, like it was before the update

**Screenshots**
see above

**System info (please complete the following information):**
Version: 1.47.0 (user setup)
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by subz390** [comment]
I also noticed that none of my favorites are showing in any of my projects.  So I tried to reinstall the Favorites extension and still nothing.  I tried to add a new favorite and I get the following,
![completelybrokennow](https://user-images.githubusercontent.com/11546815/87120680-f0cc3400-c278-11ea-82a7-a8dfdf227683.png)

Let me know if there's anything you'd like me to try if you need more info, cheers.

**Comment by shiraze** [comment]
Why was this closed? How was it fixed?

**Comment by subz390** [comment]
It got worse - I thought it was just this however later on I found the shortcuts tab was empty.  I had no shortcuts anymore.  So I in the end I uninstalled the extension.  Sorry.

**Comment by shiraze** [comment]
The bug is in VSCode v1.47.0, and should be fixed in v1.47.2.
Thanks for responding
