### ISSUE TITLE
Ability to create / move / rename / delete files in their actual structure via favorite.

### ISSUE THREAD

**Issue by Emerson-Coelho** [kdcro101/vscode-favorites#6]
Ability to create / move / rename / delete files in their actual structure via favorite.

And if possible in the move option, with drag and drop

Is it too much to ask?

lol

Your Extension is being the best for favorites!
Several friends are already using it. Congratulations for your work.

**Comment by kdcro101** [comment]
@Emerson-Coelho ,

Thank you for review.

Closing this issue after last release.
If you have any problems, open issue.
