### ISSUE TITLE
File icons disappeared after VSCode update (May 2022, version 1.68)

### ISSUE THREAD

**Issue by SergeyBeloglazovRL** [kdcro101/vscode-favorites#66]
**Describe the bug**
Icons for file have disappeared after VSCode last update (May 2022, version 1.68)

**To Reproduce**
1. Update VSCode to the last update (May 2022, version 1.68)
2. Click on favorites panel
3. Code files have no icons
![изображение](https://user-images.githubusercontent.com/67962205/173519954-a923e9ea-492d-43d0-8cda-5707f39d9b00.png)

**Expected behavior**
Files with icons, similar to the explorer panel
![изображение](https://user-images.githubusercontent.com/67962205/173520014-ac62278e-6925-4904-91b7-9f8a89263333.png)

**Screenshots**
See above

**System info (please complete the following information):**
 - OS version: Windows 10
 - Favorites extension version v2.4.5
 - vscode version 1.68.0

**Comment by emi2k01** [comment]
Fixed on vscode insiders

**Comment by GitMensch** [comment]
I guess that's also fixed in "standard" vscode now and can be closed as "not our bug, already solve", can't it?

**Comment by SergeyBeloglazovRL** [comment]
Yes, it works fine now. The issue should be closed.
Thanks!

**Comment by GitMensch** [comment]
@SergeyBeloglazovRL: you can close it yourself - otherwise only the repo owner can :-)
