### ISSUE TITLE
Cannot add files from explorer with custom titleBarStyle

### ISSUE THREAD

**Issue by tuur29** [kdcro101/vscode-favorites#7]
The setting `"window.titleBarStyle": "custom"` was introduced in the [May 2018 update](https://code.visualstudio.com/updates/v1_25#_preview-features).
When this setting is set to custom nothing happens when I click "Add to Favourites". It does show the correct popup when adding to groups. but again, nothing happens when I press enter.

I know it's only a preview not, but i wanted to give you a heads up so it can get fixed once it's out of beta.

**Comment by kdcro101** [comment]
@tuur29 ,

Thank you for your feedback.

I guess it's a bug on in Vscode https://github.com/Microsoft/vscode/issues/53665.
I can see they added it to [July 2018 milestone]( https://github.com/Microsoft/vscode/milestone/72).

Let's be patient, and see what will happen on next release.
Problem is, when command is executed from explorer it should send two parameters:
currently clicked file selected and list of selected files.  
At moment list of selected files is empty (bug) which is used for lately added functionalitiy to allow multiple selected files to be added to favorites/group.

I will try to make a fix so at least you can add currently selected file/directory in `"window.titleBarStyle": "custom"` mode, until VSCode team fixes this.

**Comment by tuur29** [comment]
Thanks for looking the issue up and providing a temporary fix!

**Comment by kdcro101** [comment]
@tuur29 ,

No problem!
Thank you for notifiying me!

**Comment by kdcro101** [comment]
@tuur29 ,

Still a problem with `1.26.0`. I can see they transfered issue to [August 2018 milestone](https://github.com/Microsoft/vscode/milestone/74)

**Comment by kdcro101** [comment]
@tuur29 ,

Problem is fixed with latest version (1.27.0)  (tested on linux).
Closing this issue.. If you have any problems, open issue.

Happy coding
