### ISSUE TITLE
File renaming error reporting

### ISSUE THREAD

**Issue by tiansin** [kdcro101/vscode-favorites#9]
OS: Win10
VSCode:1.25.1

When I use the rename function, change the file name from uppercase to lowercase, plug-in to generate the error report, and the original file is deleted.

example:
CNY.ts rename to cny.ts

**Comment by kdcro101** [comment]
@tiansin ,

Thank you for your feedback.

Please update to version 1.5.5.

Problem should be fixed.

**Comment by tiansin** [comment]
@kdcro101 
I confirm that has been fixed, thank you very much.

**Comment by kdcro101** [comment]
No problem! Thank you, again, for your feedback.
